# Numpy
- python 에서 사용하는 과학계산용 오픈소스 라이브럴
- python 의 느린 연산속도를 보안
- nadarry라는 데이터 타입을 사용합니다
- c, c++, 포트란으로 만들어짐

## 선형대수
- 스칼라(scalar)
    - 하나의 숫자로만 이루어진 데이터
- 벡터
    -여러 개의 숫자가 특정한 순서대로 모여있는것
    - 벡터([1, 2 3])
    - $\mathbf{v}=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$
- 행렬(matrix)
    - 2차원 배열로 구성
    - 행(row)과 열(colums)
    - 행렬([1, 2, 3]), [4,5,6])

In [11]:
!pip install numpy
import numpy as np

In [9]:
import numpy as np

# 01. ndarray 객체 생성

In [14]:
scalar = np.array(5)
type(scalar)

numpy.ndarray

In [17]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [19]:
matrix = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# 배열의 차원 확인
scalar.ndim, vector.ndim, matrix.ndim  # 딥러닝때 많이 씀

(0, 1, 2)

In [26]:
# 배열의 모양 확인 #딥러닝때 많이씀
scalar.shape, vector.shape, matrix.shape

((), (3,), (3, 3))

In [30]:
# 문자열도 배열 데이터 생성 가능
str_vector = np.array(list(('ABCD')))
str_vector

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [32]:
ls = [1, 2 ,3, 'D']
ls

[1, 2, 3, 'D']

In [33]:
type(ls[-1]), type(ls[0])

(str, int)

In [35]:
# numpy 는 한가지 데이터 타입으로만 인식
np.array(ls)

array(['1', '2', '3', 'D'], dtype='<U21')

In [36]:
np.array([1, 2, 3, '4']).astype(np.float64)

array([1., 2., 3., 4.])

In [37]:
np.array([1, 2, 3, '4']).astype(np.int64)

array([1, 2, 3, 4])

# 02. np.arange()

In [40]:
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
np.arange(1,5,2)

array([1, 3])

### 03. np.zeros(), np.ones()
- 0으로 채워진 행렬 데이터
- 1로 채워진 행렬 데이터
- 초기화 값을 지정할 경우 활용

In [47]:
mat_zero = np.zeros((2, 2, 3)) # 
mat_zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
mat_ones = np.ones((2, 2, 3))
mat_ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### 04. np.random()

In [76]:
# 정수 데이터 타입을 균일분포로 생성
np.random.randint(10, size = (2, 3))

array([[7, 3, 4],
       [1, 7, 2]])

In [90]:
# seed()
# seed 값을 고정하면 동일한 랜덤값 출력   # 랜덤인데 고정되어있다

np.random.seed(13)
np.random.randint(0 , 10, 10)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2])

In [104]:
np.random.choice(5, 10) # 계속 바뀐다

array([3, 0, 0, 2, 3, 2, 3, 4, 1, 0])

In [125]:
# (1) 0~4 까지 숫자 중 한개 선택
# (2) 반활할 샘플의 갯수 10개
# (3) 선택할 확률지절
# (4) 선택 할 수 있는 값의 배열과 길이가 동일해야 합니다.
np.random.choice(5, 10 , p =[0.1, 0, 0.3, 0.6,0])

array([0, 2, 2, 3, 3, 3, 3, 3, 2, 3])

# 05. np.linespace()
# 선형데이터
``` python
n[.linespace(start, stop, num = 50 endpoint = True)
```
- 시작값과 종료값 사이에서 지전된 갯수만큼 균등간격으로 선형적으로 분포하는 값 생성
- endpoint: True로 설정하면, stop 값을 배열에 포함

In [126]:
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])